### ISSUE TITLE
Failed to activate the youtube-pane package

### ISSUE THREAD

**Issue by spiritloveroot** [alexandruionascu/youtube-pane#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [youtube-pane](https://github.com/alexandruionascu/youtube-pane) package, v1.1.0
### Stack Trace

Failed to activate the youtube-pane package

```
At Cannot find module '../node_modules/jquery'

Error: Cannot find module '../node_modules/jquery'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/spirit/.atom/packages/youtube-pane/lib/youtube-pane.coffee:4:30)
    at Object.<anonymous> (/Users/spirit/.atom/packages/youtube-pane/lib/youtube-pane.coffee:84:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```
### Commands

```
     -0:57.2.0 application:new-file (atom-text-editor.editor.is-focused)
  2x -0:55 core:close (atom-text-editor.editor.is-focused)
     -0:35.1.0 window:focus-pane-on-right (atom-text-editor.editor.is-focused)
  7x -0:34.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:30.7.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:30.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
youtube-pane, v1.1.0

# Dev
No dev packages
```

**Comment by alexandruionascu** [comment]
I forgot to add dependencies...sorry, ill fix this tomorrow, npm install jquery should do it, thanks for notifying :D

**Comment by spiritloveroot** [comment]
yw&ty :)

**Comment by RafaelVidaurre** [comment]
Same with `atom-space-pen-views`

**Comment by alexandruionascu** [comment]
sorry for being a liitle late, i think i fixed it, thanks :D

**Comment by spiritloveroot** [comment]
No worries, thanks. I'll check it out later :)
